version: '3'
services:
  memento-db:
    container_name: memento-db
    image: mysql
    environment:
      MYSQL_DATABASE: memento
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dzhuliyan
      MYSQL_PASSWORD: dzhuliyan
    ports:
      - '3306:3306'
    volumes:
      - memento

  memento-server:
    restart: on-failure
    container_name: memento-server
    image: dzhuliyan/memento:memento-server
    ports:
      - '8081:8081'
    depends_on:
      - memento-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://memento-db/memento?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: dzhuliyan
      SPRING_DATASOURCE_PASSWORD: dzhuliyan

  #memento-frontend:
  #  restart: on-failure
  #  container_name: memento-frontend
  #  image: dzhuliyan/memento:memento-frontend
  # ports:
  #    - '4200:80'
  #  depends_on:
  #    - memento-server
